server:
  port: 8080

okta:
  oauth2:
    issuer: https://dev-9589469.okta.com/oauth2/default
    audience: api://default
    groups-claim: roles
    ##### Required in environment variables: ####
    # clientId:
    # clienSecret:

logging:
  level:
    org:
      springframework: DEBUG
